ADD USB CDC Transport to stm32cube framework
marecustos/micro_ros_platformio pull request #1
Opened 2024-10-09 13:34 UTC by Darouez-Oussama

2024-10-10 09:15 UTC, kaizoku-oh requested changes

2024-10-10 09:15 UTC, kaizoku-oh commented on library.json
> +        "url": "https://github.com/marecustos/micro_ros_platformio#USB-CDC"
`USB-CDC` -> `stm32cube`

2024-10-10 09:15 UTC, kaizoku-oh commented on platform_code/stm32cube/usb/micro_ros_transport.cpp
> +extern PCD_HandleTypeDef hpcd_USB_OTG_FS;
Is this used here?

2024-10-10 09:16 UTC, kaizoku-oh commented
Can you please this file and only change what needs to be changed?

https://github.com/marecustos/micro_ros_platformio/blob/4251724ec5cbc77c7dd20189cc1a6991252ac897/platform_code/stm32cube/usb/micro_ros_transport.cpp

2024-10-10 11:19 UTC, Darouez-Oussama commented on platform_code/stm32cube/usb/micro_ros_transport.cpp
> +extern PCD_HandleTypeDef hpcd_USB_OTG_FS;
no it is not used i will remove it

2024-10-10 11:32 UTC, Darouez-Oussama commented
i have changed #USB-CDC to #stm32cube 
and removed the extern PCD_HandleTypeDef hpcd_USB_OTG_FS; because it is not used

2024-10-10 13:32 UTC, bayrem-gharsellaoui commented
> Can you please base your work on this file and only change what needs to be changed?
> 
> https://github.com/micro-ROS/micro_ros_stm32cubemx_utils/blob/jazzy/extra_sources/microros_transports/usb_cdc_transport.c

@Darouez-Oussama

2024-10-10 17:14 UTC, Darouez-Oussama commented
I did not understand this . 
do i go to this link and enter github dev make the changes needed and commit ? 
https://github.com/marecustos/micro_ros_platformio/blob/4251724ec5cbc77c7dd20189cc1a6991252ac897/platform_code/stm32cube/usb/micro_ros_transport.cpp

2024-10-18 10:11 UTC, kaizoku-oh approved these changes

2024-10-19 16:01 UTC, merged